### ISSUE TITLE
必要なオブジェクトとフィールドを決める

### ISSUE THREAD

**Issue by hitochan777** [steadiley/taskee#10]
ER図的なものを作ってみる。

@hanahageWanko どういうデータ構造が必要かは重要だと思うのでアイデアをお待ちしてます。

以下はまだ途中。

* UserSetting
  * visual_mode: "light" or "dark"
  * timezone
* Task
  * id
  * title
  * due_date
  * created_by
  * done
  * created_at
* TaskEvent: タスクの変化 (スタートボタン押下、ストップボタン押下などのイベントを保持)
  * name
  * task_id
  * created_at

**Comment by hanahageWanko** [comment]
@hitochan777 
ほぼ現状の画面設計書から読み取れるものは網羅しているように思います。

下記確認です。
1. 認証情報やログイン状態を判断するは別ということで良いですか？
1. TaskEventのcreated_atを今(new Date()?)の時間から引いたものを経過時間として扱う認識であってますか？
1. task_idでin progress状態を判断するという認識であってますか？
1. Task.crated_byはなんの役割ですか？

**Comment by hanahageWanko** [comment]
後、これは全然後でも良いと思うのですが、
ログを見る時(グラフを見る時)に、
日毎だけじゃなくて、
「どんなジャンルのタスクに時間を使っているのか」
「どんなジャンルのタスクが多いのか」とかは知りたいんじゃないかなって思うんで、
タグ機能はほしくないですか？
なので、下記追加はどうでしょう？
```
Task
 * tag_id
Tag
 * id
 * title
 * color
```
...今じゃなくても全然問題ないと思いますが、
後々になると、それまでに作ったタスクにタグをつけていくのがすごく手間だと思うので、
フィールドは作っておいて、画面の方はコーディングしていく中ですり合わせしていくのはどうでしょうか？

**Comment by hitochan777** [comment]
> 認証情報やログイン状態を判断するは別ということで良いですか？

これはFirebaseがAuthenticationというものを提供しているのでこれで行けると思います。Azure B2Cみたいな感じのものです。

> TaskEventのcreated_atを今(new Date()?)の時間から引いたものを経過時間として扱う認識であってますか？

Taskに紐付いた最新のTaskEventが開始イベントであれば、そのnew Date()からcreated_atを引いた値が経過時間ですね。

> task_idでin progress状態を判断するという認識であってますか？

TaskとTaskEventは一対多の関係にあります。
例えばですが下記の一行それぞれが1つのTaskEventです。
これによってグラフを出すときにいつからいつまでどのタスクに時間を費やしたか、
トータルで何分使ったかが計算できるようになります。

10:20 開始
10:30 停止
11:22 開始
11:24 停止 

> Task.crated_byはなんの役割ですか？
どのユーザのタスクかを識別するためのものですが、firestoreを使うのであれば不要かも知れません。要調査です。

**Comment by hitochan777** [comment]
確かにタグはあったほうがいいですね。
ただ、タグのフィールドは後から追加もできますし、後から追加したときにタグのフィールドがないタスクに関してはタグがついていないタスクとして扱ってもいいかなと思ってます。

**Comment by hanahageWanko** [comment]
@hitochan777 
> どのユーザのタスクかを識別するためのものですが、firestoreを使うのであれば不要かも知れません。要調査です。
これは別途ISSUEを立てますか？
それとも本イシューの追加対象としますか？

**Comment by hanahageWanko** [comment]
> 確かにタグはあったほうがいいですね。
> ただ、タグのフィールドは後から追加もできますし、後から追加したときにタグのフィールドがないタスクに関してはタグがついていないタスクとして扱ってもいいかなと思ってます。
OKです。
であれば、私はISSUE本文ないのオブジェクト/フィールドの内容で行けると思います。

**Comment by hitochan777** [comment]
@hanahageWanko 
> これは別途ISSUEを立てますか？
それとも本イシューの追加対象としますか？

firestoreはドキュメントをネストできるため、下記のようなデータ構造でどうでしょうか？

```
users
  {userId}
    tasks
      {taskId}
        events
          {eventId}
```

**Comment by hanahageWanko** [comment]
@hitochan777 
ドキュメントがネストできるのめちゃくちゃ便利ですね！
それでいきましょう！
私の備忘録的に下記にドキュメントを貼っておきます。
https://firebase.google.com/docs/firestore/manage-data/structure-data?hl=ja

**Comment by hitochan777** [comment]
ありがとうございます！ではクローズします。
