### ISSUE TITLE
グローバルスタイルの作成

### ISSUE THREAD

**Issue by hanahageWanko** [steadiley/taskee#12]
@hitochan777 
CSSフレームワークはオリジナルで作るとして、「initialize.css & normalize.css」または「reset.css」はどうしますか？

**Comment by hitochan777** [comment]
initialize.cssというのはそういうライブラリがあるのですか？

**Comment by hanahageWanko** [comment]
@hitochan777 
いえ、下記の認識です。
initialize.css(≒reset.css)
normalize.css

オリジナルで作る場合は、
大体が下記の2パターンかなと思います。
①異なることで致命的となる箇所を初期化+各ブラウザごとで異なっても良いところは生かす(normalize.css)
initialize.css(reset.css)を作成して、全ブラウザごとのクセ(異なる挙動)を初期化する
     => どのブラウザも大体同じstyleにすることができる
     => その上で、normalize.cssでオリジナルのグローバルルールを設定
②ブラウザごとで異なる可能性のある箇所を全て初期化(reset.css)
     => どのブラウザも大体同じstyleにすることができる

reset.cssはcssライブラリとしてオープンソースのものもありますが、
initialize.css , normalize.cssの考え方は、より自由度を増したものにまります。
なので、「initialize.cssとreset.cssは人によっては同義に扱われることもあるが、normalize.cssを追加するとこを前提とした時は、reset.cssとは異なる考え方をする必要がある」というイメージです。

**Comment by hitochan777** [comment]
なるほど。ありがとうございます。(今まで曖昧な理解だったので...)

reset.css使うと全てstyleを初期化するので、CSSの記述量が増えますよね...?
normalize.cssで良い気がします。

**Comment by hanahageWanko** [comment]
@hitochan777 
OKです。では、例えばhtmlタグやbodyタグのmargin,paddingなどを全ブラウザで統一するための最低限のスタイル調整としてinitialize.cssを作成。
box-sizing:border-boxなどを含め、グローバルなルールとして設定するスタイルをnormalize.cssとして作成。
という認識で良いでしょうか？

**Comment by hitochan777** [comment]
@hanahageWanko そうしましょう!

**Comment by hanahageWanko** [comment]
- [ ] initialize.scss // 初期化
- [ ] normalize.scss // 汎用化
- [ ] module.scss // フレームワークとして使うclassを定義
- [ ] valueble.scss // 変数を定義
- [ ] mixin.scss // メソッド類はここ
上記を作成

**Comment by hitochan777** [comment]
コンポーネント内で各々スタイリングしていくのでmodule.scssは不要でよいですか？
であれば、クローズしてもいいですかね。

**Comment by hanahageWanko** [comment]
> コンポーネント内で各々スタイリングしていくのでmodule.scssは不要でよいですか？

はい。不要です。クローズします。
