### ISSUE TITLE
画面設計書を作成する

### ISSUE THREAD

**Issue by hitochan777** [steadiley/taskee#2]

**Comment by hanahageWanko** [comment]
どれだけのページがいるのかわかっていないのですが、
ざっとこのくらいですか？
### 必要画面
- 記録確認画面
  - グラフ
- タスク登録/一覧/削除/更新画面
  - 日毎の一覧
- 過去のタスク確認画面
- ラベル一覧/ラベル絞り込みタスク一覧画面

おそらくもっとたくさん出てくると思うけど、
そこは都度対応にします？

**Comment by hanahageWanko** [comment]
ベースイメージとしては、togglみたいな感じで良い？

**Comment by hitochan777** [comment]
ベースはboostedみたいなのを想定していました！

**Comment by hanahageWanko** [comment]
画面設計の方向性としては
スマホデザインを先に作成　＝＞　その後、PCデザインの方向性で良い？

**Comment by hitochan777** [comment]
そうしましょう！

**Comment by hitochan777** [comment]
今思い出しましたけど、サインアップ、ログイン画面も必要ですね...

**Comment by hanahageWanko** [comment]
@hitochan777 
1. サインイン
2. サインアウト
3. todayタスク一覧
4. Quick add
5. Backlog 
6. Next 7days page
ひとまず6ページ分ですかね？

**Comment by hanahageWanko** [comment]
カラーリングに迷っています。
一度タスクを開始して、停止をしたものはチェックをつけてグリーンにしています。
デザインイメージのすり合わせをしてから残りのページ分を一気に仕上げようと思っているので、
いったん感想いただけたらと...
![image](https://user-images.githubusercontent.com/43740354/79238159-03b5af00-7eaa-11ea-87cd-11c486753562.png)

**Comment by hitochan777** [comment]
@hanahageWanko 
そうですね。サインアップは基本ソーシャルログインで良いかなと(TwitterやGoogleなど)と思ってます。

カラーリングしていただきありがとうございます！ いい感じだと思います。ダークモードにしていただいてるんですね。(両方欲しい気もしますが、まずはダークモードで行きますか！）

> 一度タスクを開始して、停止をしたものはチェックをつけてグリーンにしています。

タスクを開始して停止してもチェックはつかないというイメージだったんですが、どうでしょうか? ユーザが明示的にチェックを入れないといけない感じです。(あと、チェックが入っているタスクはチェックを外さない限り再生ボタンを押せなくするようにしてもいいかもです。)

**Comment by hanahageWanko** [comment]
@hitochan777 
> 両方欲しい気もしますが、まずはダークモードで行きますか！
両方のパターンは私も考えています。
こちらのカラーリングで進めるなら、ライトモードも作成しておきます。

> ユーザが明示的にチェックを入れないといけない感じです。
別途でお話しさせていただいたかと思うのですが、
認識が曖昧な感じでした。失礼しました。
・タスクはCLICKで、停止<=>開始の状態を切り替えることができる。
・タスクにチェックをつけるとdisabledの状態になる。
・チェックを外すとCLICKで、停止<=>開始の状態を切り替えることができるようになる。
上記認識であってますか？

後、タスクが完了したかどうかは「チェックの有無」で判断する認識ですか？
それとも「チェックがついているタスク郡を完了」とするボタンか何かがあるイメージですか？

**Comment by hitochan777** [comment]
> こちらのカラーリングで進めるなら、ライトモードも作成しておきます。

お願いします！
* タスクは右側の再生ボタンを押すことで停止と開始の状態を切り替えることができる
* タスクにチェックを入れるとタスクは完了済みとなり、再生ボタンがdisabledになる

> チェックを外すとCLICKで、停止<=>開始の状態を切り替えることができるようになる。

これはOKです！

> 後、タスクが完了したかどうかは「チェックの有無」で判断する認識ですか？

そうです！

**Comment by hanahageWanko** [comment]
了解です。

@hitochan777 
> タスクが完了したかどうかは「チェックの有無」で判断
Backlogにはチェックタスクにチェックがついた時点で表示されるようになる。
ということですか？
それとも、チェックがつくことで完了状態にはなるけれども、Backlogに含まれるようになるのは別の条件(例えば時間や日)がある認識ですか？

**Comment by hitochan777** [comment]
バックログはチェックがついたかどうかは全く関係がなく、スケジュールが登録されていないものが表示されるだけです。スケジュールが登録されているものはTodayやNext 7 Daysに表示されます。
この辺の説明が足りてなかったですね。すいません！

**Comment by hanahageWanko** [comment]
@hitochan777 
リンク更新しています。
https://xd.adobe.com/view/d58e6a6c-0509-434f-4bad-3ef597c7ab26-a3bf/
フッターの「Light mode」「Dark mode」を押すとお互いのモードを行き来できます。
ご確認お願いします。

**Comment by hitochan777** [comment]
ありがとうございます！良いと思います。

**Comment by hanahageWanko** [comment]
一旦擦り合わせはできたので、Closeします。
