### ISSUE TITLE
ESLintのエラーをきつくする

### ISSUE THREAD

**Issue by hitochan777** [steadiley/taskee#8]
現状等価演算子が==でも通ってしまうので===でないとエラーになるようにする。

**Comment by hitochan777** [comment]
等価演算子だけでなく、他のエラーもできれば追加したいです。

**Comment by hanahageWanko** [comment]
"extends": "eslint:recommended"
上記のルールを追加するというのはどうでしょう？
https://eslint.org/docs/rules/
それと同時にhuskyも導入して、commit前に"lint --fix"を走らせるのはどうでしょうか？
そうすれば、上記URLの厳密等価演算子などのレンチマークのついているルールにも適応できるのではないでしょうか？

**Comment by hitochan777** [comment]
いい感じですね。そうしましょう！

**Comment by hanahageWanko** [comment]
すみません。
上記勘違いしてました。
"eslint:recommended"のルール(添付URLのチェックがついている行)のルールは現在的すでに適用されているようです。
なので、追加ルールだけを追記していかなければならないです。
ざっと見た感じでは、eqeqeqの厳格等価演算子のルールのみ追加で良いのではないかなと思うのですが、どうでしょうか？
huskyは入れようと思います。

**Comment by hitochan777** [comment]
なるほど。そういうことでしたか。
eqeqeqぐらいでと思います。

**Comment by hitochan777** [comment]
huskyも入れてもらって構いません :smile:
